[phases.setup]
nixPkgs = ['python311', 'gcc']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0: --chdir backend app_structured:app'
