[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python backend/app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
PYTHONPATH = "/app/backend"
